"""Phase 2 extra workers — Accounts, Quantum, Lifts, Training, Model Ops, etc.

Appended to the worker_registry on first read. Designed to push the
total worker count to 150+ with real, named, badge-tagged staff.
"""

EXTRA = [
    # ── Accounts Department (floor 44) ─────────────────────────────
    {"display_name": "Chief Accounts Officer",     "role": "Chief of Accounts Department — reports to Governance Zone Manager.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Chief Office",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Accounts Floor Manager",     "role": "Floor manager for Floor 44.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Floor Manager Office",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Tower Ledger Accountant",    "role": "Tower-wide ledger summary reporting.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Ledger Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "OANDA Floor Accountant",     "role": "Floor 41 OANDA telemetry summary (read-only).",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "OANDA Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Binance Floor Accountant",   "role": "Floor 42 Binance telemetry summary (read-only).",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Binance Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Stocks Floor Accountant",    "role": "Floor 43 Stocks telemetry summary (read-only).",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Stocks Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "AirLLM Accountant",          "role": "AirLLM chamber storage + usage summary.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "AirLLM Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Research Accountant",        "role": "Research task budget summary.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Research Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Maintenance Accountant",     "role": "Maintenance department cost summary.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Maintenance Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Security Accountant",        "role": "Security incident audit summary.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Security Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "IT Accountant",              "role": "IT/Networking operational summary.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "IT Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Penthouse Accountant",       "role": "Penthouse operations summary.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Penthouse Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Audit Accountant",           "role": "Audit ledger summary cross-check.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Audit Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Paper Ledger Clerk",         "role": "Floor 41 paper ledger summary.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Paper Ledger Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "P&L Verification Clerk",     "role": "Verifies P&L labels (LIVE/PAPER/NOT_CONFIGURED).",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Verification Desk",
     "team": "accounts", "stage": "active_advisory"},
    {"display_name": "Not Configured Data Clerk",  "role": "Catalogs every endpoint currently reporting not_configured.",
     "floor_assignment": "floor_44", "department": "Accounts Department", "desk_assignment": "Not Configured Board",
     "team": "accounts", "stage": "active_advisory"},

    # ── Quantum Floor (floor 45) ──────────────────────────────────
    {"display_name": "Quantum Floor Manager",      "role": "Floor manager for Floor 45.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Floor Manager Office",
     "team": "quantum", "stage": "active_advisory"},
    {"display_name": "Quantum Systems Researcher", "role": "Local quantum runtime detection + reporting.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Reactor Room",
     "team": "quantum", "stage": "active_advisory"},
    {"display_name": "Quantum Entropy Clerk",      "role": "Entropy/variance placeholder reporting.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Entropy Monitor",
     "team": "quantum", "stage": "active_advisory"},
    {"display_name": "Quantum Symbolic Analyst",   "role": "Quantum symbolic state analysis.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Symbolic Desk",
     "team": "quantum", "stage": "active_advisory"},
    {"display_name": "Quantum Model Liaison",      "role": "Bridges Quantum lab and Model Operations.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Model Liaison Desk",
     "team": "quantum", "stage": "active_advisory"},
    {"display_name": "Quantum Safety Auditor",     "role": "Verifies quantum lab does not enable execution.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Safety Gate",
     "team": "quantum", "stage": "active_advisory"},
    {"display_name": "Quantum Packet Runner",      "role": "Routes quantum advisory packets toward Kernel.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Packet Run Desk",
     "team": "quantum", "stage": "active_advisory"},
    {"display_name": "Quantum Lab Accountant",     "role": "Quantum lab cost + usage summary.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Accountant Card",
     "team": "quantum", "stage": "active_advisory"},
    {"display_name": "Quantum Overseer",           "role": "Overseer for Floor 45.",
     "floor_assignment": "floor_45", "department": "Quantum Operations Department", "desk_assignment": "Overseer Balcony",
     "team": "quantum", "stage": "active_advisory"},

    # ── Lifts / Logistics (floor 22 — Integration Services) ────────
    {"display_name": "Lift Operations Manager",    "role": "Coordinates 9 lifts across all floors.",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Lift Ops Office",
     "team": "logistics", "stage": "active_advisory"},
    {"display_name": "Lift Controller 01",         "role": "Operates Lift-01 (low-rise main).",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Lift-01 Console",
     "team": "logistics", "stage": "active_read_only"},
    {"display_name": "Lift Controller 02",         "role": "Operates Lift-02 (mid-rise main).",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Lift-02 Console",
     "team": "logistics", "stage": "active_read_only"},
    {"display_name": "Lift Controller 03",         "role": "Operates Lift-03 (high-rise main).",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Lift-03 Console",
     "team": "logistics", "stage": "active_read_only"},
    {"display_name": "Lift Controller 04",         "role": "Operates Lift-04 (express).",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Lift-04 Console",
     "team": "logistics", "stage": "active_read_only"},
    {"display_name": "Worker Routing Clerk",       "role": "Coordinates worker-to-floor routing.",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Routing Desk",
     "team": "logistics", "stage": "active_advisory"},
    {"display_name": "Packet Routing Clerk",       "role": "Coordinates packet-to-floor routing.",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Packet Desk",
     "team": "logistics", "stage": "active_advisory"},
    {"display_name": "Floor Traffic Controller",   "role": "Tower-wide traffic coordination.",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Traffic Console",
     "team": "logistics", "stage": "active_advisory"},
    {"display_name": "Logistics Accountant",       "role": "Lift/Logistics operational summary.",
     "floor_assignment": "floor_22", "department": "Lift / Logistics", "desk_assignment": "Accountant Card",
     "team": "logistics", "stage": "active_advisory"},

    # ── Training Academy (floor 8 — Testing Department) ────────────
    {"display_name": "Training Academy Manager",   "role": "Floor manager for Floor 8 Training Academy.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Academy Office",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Worker Trainer",             "role": "General worker training programs.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Training Hall",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "OpenClaw Readiness Trainer", "role": "Prepares workers for OpenClaw readiness review.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "OpenClaw Training Room",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Security Training Clerk",    "role": "Security awareness training.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Security Training Room",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Trading Telemetry Trainer",  "role": "Read-only trading telemetry training.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Telemetry Room",
     "team": "training", "stage": "active_advisory"},

    # ── V3 Training Academy reinforcement — 13 more teachers ──────
    {"display_name": "Curriculum Director",        "role": "Owns the 21-course curriculum.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Certification Board",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Worker Induction Teacher",   "role": "Runs QSB Induction + Worker Badge & Identity courses.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Reception / Intake Desk",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Safety Locks Teacher",       "role": "Teaches Safety Locks 101.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Safety and Locks Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "OpenClaw Readiness Teacher", "role": "Teaches OpenClaw Readiness, Not Execution.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "OpenClaw Readiness Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Research Methods Teacher",   "role": "Teaches Research Quality + Source Checking.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Research Methods Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "IT Networking Teacher",      "role": "Teaches IT + Local Sidecars.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "IT / Networking Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Maintenance Training Officer","role": "Teaches Maintenance Monitoring.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Maintenance Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Accounts Tutor",             "role": "Teaches Accounts and P&L Labels.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Accounts Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Quantum Tutor",              "role": "Teaches Quantum Safety + Symbolic Lab.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Quantum Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Kernel Communication Tutor", "role": "Teaches Kernel Communication.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Kernel Etiquette Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Speech / Media Tutor",       "role": "Teaches Speech and Media Controls.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Kernel Etiquette Classroom",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Exam Invigilator",           "role": "Runs the Exam Room.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Exam Room",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Certification Clerk",        "role": "Issues + revokes certifications.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Certification Board",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Training Floor Accountant",  "role": "Academy operational summary.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Training Accountant Card",
     "team": "training", "stage": "active_advisory"},
    {"display_name": "Training Overseer",          "role": "Overseer for Floor 8 — flags uncertified sensitive workers.",
     "floor_assignment": "floor_08", "department": "Training Academy", "desk_assignment": "Training Overseer Balcony",
     "team": "training", "stage": "active_advisory"},

    # ── V4 Trading Shift on Floor 41 (OANDA Practice) ──────────────────
    {"display_name": "Practice Order Guard",        "role": "Last-line guard before any practice order is placed.",
     "floor_assignment": "floor_41", "department": "OANDA Practice Trading Floor", "desk_assignment": "Risk Guard Station",
     "team": "trading_fx", "stage": "active_advisory"},
    {"display_name": "Practice Execution Clerk",    "role": "Places approved practice orders via the guarded gateway.",
     "floor_assignment": "floor_41", "department": "OANDA Practice Trading Floor", "desk_assignment": "Practice Execution Desk",
     "team": "trading_fx", "stage": "active_advisory"},
    {"display_name": "OpenClaw Practice Liaison",   "role": "Routes OpenClaw practice proposals to manual confirm.",
     "floor_assignment": "floor_41", "department": "OANDA Practice Trading Floor", "desk_assignment": "OpenClaw Practice Proposal Desk",
     "team": "openclaw_advisory", "stage": "active_advisory"},
    {"display_name": "Kernel Trading Reporter",     "role": "Sends trading summaries to Kernel review.",
     "floor_assignment": "floor_41", "department": "OANDA Practice Trading Floor", "desk_assignment": "Manager Office",
     "team": "trading_fx", "stage": "active_advisory"},

    # ── Data/Memory Department (floor 2 — Memory Department) ──────
    {"display_name": "Memory Floor Manager",       "role": "Floor manager for Floor 2 Memory.",
     "floor_assignment": "floor_02", "department": "Memory Department", "desk_assignment": "Memory Floor Office",
     "team": "data_memory", "stage": "active_advisory"},
    {"display_name": "State Archivist",            "role": "Archives tower state snapshots.",
     "floor_assignment": "floor_02", "department": "Memory Department", "desk_assignment": "Archive Desk",
     "team": "data_memory", "stage": "active_advisory"},
    {"display_name": "Vector Memory Clerk",        "role": "Manages vector memory shelf.",
     "floor_assignment": "floor_02", "department": "Memory Department", "desk_assignment": "Vector Shelf",
     "team": "data_memory", "stage": "active_advisory"},
    {"display_name": "SQLite Memory Clerk",        "role": "Manages structured memory tables.",
     "floor_assignment": "floor_02", "department": "Memory Department", "desk_assignment": "SQLite Shelf",
     "team": "data_memory", "stage": "active_advisory"},
    {"display_name": "Report Archivist",           "role": "Archives manager + overseer reports.",
     "floor_assignment": "floor_02", "department": "Memory Department", "desk_assignment": "Report Archive",
     "team": "data_memory", "stage": "active_advisory"},
    {"display_name": "Kernel Memory Liaison",      "role": "Liaises memory routes with Kernel.",
     "floor_assignment": "floor_02", "department": "Memory Department", "desk_assignment": "Kernel Liaison Desk",
     "team": "data_memory", "stage": "active_advisory"},
    {"display_name": "Data Integrity Auditor",     "role": "Audits data integrity (read-only).",
     "floor_assignment": "floor_02", "department": "Memory Department", "desk_assignment": "Integrity Desk",
     "team": "data_memory", "stage": "active_advisory"},

    # ── Model Operations (floor 24 — Model Routing Department) ────
    {"display_name": "Model Operations Manager",   "role": "Floor manager for Floor 24 Model Routing.",
     "floor_assignment": "floor_24", "department": "Model Operations", "desk_assignment": "Floor Manager Office",
     "team": "model_ops", "stage": "active_advisory"},
    {"display_name": "Ollama Lane Technician",     "role": "Maintains Ollama lane health.",
     "floor_assignment": "floor_24", "department": "Model Operations", "desk_assignment": "Ollama Desk",
     "team": "model_ops", "stage": "active_advisory"},
    {"display_name": "Local Model Monitor",        "role": "Monitors local model lane.",
     "floor_assignment": "floor_24", "department": "Model Operations", "desk_assignment": "Local Model Desk",
     "team": "model_ops", "stage": "active_read_only"},
    {"display_name": "AirLLM Advisory Monitor",    "role": "Monitors AirLLM advisory lane (read-only).",
     "floor_assignment": "floor_24", "department": "Model Operations", "desk_assignment": "AirLLM Desk",
     "team": "model_ops", "stage": "active_advisory"},
    {"display_name": "Model Router Clerk",         "role": "Routes queries to local/advisory lanes only.",
     "floor_assignment": "floor_24", "department": "Model Operations", "desk_assignment": "Router Desk",
     "team": "model_ops", "stage": "active_advisory"},
    {"display_name": "Prompt Quality Auditor",     "role": "Audits prompt quality (advisory only).",
     "floor_assignment": "floor_24", "department": "Model Operations", "desk_assignment": "Audit Desk",
     "team": "model_ops", "stage": "active_advisory"},
    {"display_name": "Model Accountant",           "role": "Model lane usage summary.",
     "floor_assignment": "floor_24", "department": "Model Operations", "desk_assignment": "Accountant Card",
     "team": "model_ops", "stage": "active_advisory"},

    # ── Compliance / Legal (floor 32 — Compliance Department) ─────
    {"display_name": "Compliance Floor Manager",   "role": "Floor manager for Floor 32 Compliance.",
     "floor_assignment": "floor_32", "department": "Compliance Department", "desk_assignment": "Floor Manager Office",
     "team": "compliance", "stage": "active_advisory"},
    {"display_name": "Financial Disclaimer Clerk", "role": "Maintains 'not financial advice' disclaimers.",
     "floor_assignment": "floor_32", "department": "Compliance Department", "desk_assignment": "Disclaimer Desk",
     "team": "compliance", "stage": "active_advisory"},
    {"display_name": "Permission Policy Clerk",    "role": "Catalogs permission policies.",
     "floor_assignment": "floor_32", "department": "Compliance Department", "desk_assignment": "Policy Desk",
     "team": "compliance", "stage": "active_advisory"},
    {"display_name": "Credential Policy Clerk",    "role": "Catalogs credential handling policies.",
     "floor_assignment": "floor_32", "department": "Compliance Department", "desk_assignment": "Credential Desk",
     "team": "compliance", "stage": "active_advisory"},
    {"display_name": "Audit Compliance Officer",   "role": "Cross-checks audit + compliance.",
     "floor_assignment": "floor_32", "department": "Compliance Department", "desk_assignment": "Cross-Check Desk",
     "team": "compliance", "stage": "active_advisory"},
    {"display_name": "Risk Compliance Accountant", "role": "Risk & compliance accounting summary.",
     "floor_assignment": "floor_32", "department": "Compliance Department", "desk_assignment": "Risk Desk",
     "team": "compliance", "stage": "active_advisory"},

    # ── Emergency Control (floor 29 — Guardian Department) ───────
    {"display_name": "Emergency Control Manager",  "role": "Floor manager for Floor 29 Emergency.",
     "floor_assignment": "floor_29", "department": "Emergency Control Room", "desk_assignment": "Emergency Office",
     "team": "emergency_control", "stage": "active_advisory"},
    {"display_name": "Incident Dispatcher",        "role": "Coordinates inbound incidents.",
     "floor_assignment": "floor_29", "department": "Emergency Control Room", "desk_assignment": "Dispatch Desk",
     "team": "emergency_control", "stage": "active_advisory"},
    {"display_name": "Critical Alert Clerk",       "role": "Catalogs critical alerts.",
     "floor_assignment": "floor_29", "department": "Emergency Control Room", "desk_assignment": "Alert Board",
     "team": "emergency_control", "stage": "active_advisory"},
    {"display_name": "Fallback Route Controller",  "role": "Maintains fallback routing logic.",
     "floor_assignment": "floor_29", "department": "Emergency Control Room", "desk_assignment": "Fallback Console",
     "team": "emergency_control", "stage": "active_advisory"},
    {"display_name": "Shutdown Policy Clerk",      "role": "Documents shutdown policies (does not execute).",
     "floor_assignment": "floor_29", "department": "Emergency Control Room", "desk_assignment": "Policy Desk",
     "team": "emergency_control", "stage": "active_advisory"},
]
