#!/usr/bin/env bash
# qsb_set_alpaca_paper_keys.sh
#
# Interactive helper to install Alpaca PAPER-TRADING API credentials
# for Floor 43's stock paper-trading engine.
#
#   * Reads keys from your terminal — silent input, never echoed.
#   * Writes floors/floor_28_security_department/vault/.env.alpaca_paper
#   * chmod 600 on the env file (owner-read/write only).
#   * Smoke-tests the keys via a read-only call to paper-api.alpaca.markets.
#
# This is for the Alpaca PAPER environment (fake money) only.
# Get paper keys from https://alpaca.markets — log in, switch to "Paper",
# then API Keys → Generate. These are different from live keys.
#
# Re-run any time to overwrite. Existing values are not displayed.

set -euo pipefail

ROOT="/vaults/nvme0/qsb_tower_v1"
VAULT_DIR="$ROOT/floors/floor_28_security_department/vault"
ENV_FILE="$VAULT_DIR/.env.alpaca_paper"
GITIGNORE="$ROOT/.gitignore"
PAPER_URL="https://paper-api.alpaca.markets"

mkdir -p "$VAULT_DIR" && chmod 700 "$VAULT_DIR"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Alpaca PAPER key installer · QSB Tower Floor 43"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
echo " You are about to install PAPER-TRADING keys (fake money)."
echo " Get them from: https://alpaca.markets  →  switch to PAPER  →  API Keys"
echo " DO NOT paste your LIVE Alpaca keys here — those control real money"
echo " and this script does not gate real-money execution."
echo
read -rp " Continue? [y/N] " confirm
case "$confirm" in
  y|Y|yes|YES) ;;
  *) echo " aborted."; exit 1 ;;
esac

# Read the API key — visible, since it isn't sensitive on its own
echo
echo " Paste your PAPER API KEY ID then press Enter."
echo " (this is the 'Key ID' string from alpaca.markets paper console)"
read -rp " API KEY ID: " API_KEY
API_KEY="$(echo "$API_KEY" | tr -d '[:space:]')"
if [ -z "$API_KEY" ]; then
  echo " no api key entered — aborting"
  exit 1
fi

# Read the secret — silent, never echoed, never in history
echo
echo " Paste your PAPER API SECRET then press Enter."
echo " (input is hidden; you won't see anything as you paste)"
read -rsp " API SECRET: " API_SECRET
echo
API_SECRET="$(echo "$API_SECRET" | tr -d '[:space:]')"
if [ -z "$API_SECRET" ]; then
  echo " no api secret entered — aborting"
  exit 1
fi

# Write the env file with restricted perms
umask 077
cat > "$ENV_FILE" <<EOF
# Alpaca PAPER credentials — fake money only.
# Generated by scripts/qsb_set_alpaca_paper_keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# DO NOT commit. DO NOT share. DO NOT put live-trading keys here.
ALPACA_API_KEY=$API_KEY
ALPACA_API_SECRET=$API_SECRET
ALPACA_ENV=paper
ALPACA_READ_ONLY=true
ALPACA_ORDER_EXECUTION_ENABLED=false
EOF
chmod 600 "$ENV_FILE"
echo " wrote $ENV_FILE  (mode 600, owner-only)"

# Make sure .gitignore covers it
if [ -f "$GITIGNORE" ]; then
  if ! grep -qE '^\.env(\.|$|\*)' "$GITIGNORE"; then
    {
      echo ""
      echo "# QSB Tower — env files with credentials. Never commit."
      echo ".env"
      echo ".env.*"
      echo "floors/floor_28_security_department/vault/"
    } >> "$GITIGNORE"
    echo " added .env / .env.* / vault to .gitignore"
  fi
fi

# Smoke test — read-only signed call (GET /v2/account)
echo
echo " Testing keys against $PAPER_URL/v2/account ..."
set +e
CODE=$(curl -s -o /tmp/qsb_alpaca_test.json -w "%{http_code}" \
  -H "APCA-API-KEY-ID: $API_KEY" \
  -H "APCA-API-SECRET-KEY: $API_SECRET" \
  "$PAPER_URL/v2/account" 2>/dev/null)
set -e

if [ "$CODE" = "200" ]; then
  echo " ✓ keys verified against Alpaca paper (HTTP 200)"
  if command -v python3 >/dev/null 2>&1; then
    python3 -c "
import json
try:
    d = json.load(open('/tmp/qsb_alpaca_test.json'))
    print(f'   account status: {d.get(\"status\",\"—\")}')
    print(f'   pattern day trader: {d.get(\"pattern_day_trader\",\"—\")}')
    print(f'   trading blocked: {d.get(\"trading_blocked\",\"—\")}')
    print(f'   cash: {d.get(\"cash\",\"—\")}  buying power: {d.get(\"buying_power\",\"—\")}')
except Exception as e:
    print(f'   (parse error: {e})')
"
  fi
else
  echo " ✗ key test failed (HTTP $CODE)"
  echo "   response: $(head -c 240 /tmp/qsb_alpaca_test.json)"
  echo
  echo "   common causes:"
  echo "    · keys from live Alpaca used against paper endpoint → wrong"
  echo "    · keys revoked or regenerated"
  echo "    · paper account not yet activated"
  exit 2
fi
rm -f /tmp/qsb_alpaca_test.json

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Keys installed and verified."
echo
echo " The dashboard launcher (scripts/qsb_dashboard_start.sh) auto-sources"
echo " every .env.* file in the Floor 28 vault — already wired."
echo
echo " To use right now in your current shell:"
echo "   set -a; source $ENV_FILE; set +a"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
