#!/usr/bin/env bash
# qsb_set_deepseek_keys.sh
#
# Interactive helper to install DeepSeek API credentials into the Floor 28 vault.
#
# IMPORTANT:
#   Storing the key DOES NOT enable provider execution. CLAUDE.md V1.5 keeps
#   these gates locked false:
#     · direct_provider_access
#     · external_provider_execution_enabled
#     · model_inference_enabled
#   The key sits in the vault. Nothing in the codebase calls DeepSeek today.
#   To USE the key, those gates need to be flipped via a CLAUDE.md edit
#   (not a verbal directive).
#
# What this script does:
#   1. Confirms storage intent
#   2. Reads DEEPSEEK_API_KEY (hidden)
#   3. Writes floors/floor_28_security_department/vault/.env.deepseek (chmod 600)
#   4. Tests via GET /models (read-only)
#   5. Reports back with no key material in stdout/logs

set -euo pipefail

ROOT="/vaults/nvme0/qsb_tower_v1"
VAULT_DIR="$ROOT/floors/floor_28_security_department/vault"
ENV_FILE="$VAULT_DIR/.env.deepseek"
GITIGNORE="$ROOT/.gitignore"
DEEPSEEK_BASE="https://api.deepseek.com"

mkdir -p "$VAULT_DIR" && chmod 700 "$VAULT_DIR"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " DeepSeek key installer · QSB Tower Floor 28 vault"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
echo " This stores the key. It does NOT enable provider access."
echo " direct_provider_access stays FALSE — no code calls DeepSeek today."
echo
read -rp " Continue? [y/N] " confirm
case "$confirm" in
  y|Y|yes|YES) ;;
  *) echo " aborted."; exit 1 ;;
esac

# Hidden API key
echo
echo " Paste your DEEPSEEK_API_KEY (sk-...) then press Enter."
echo " (input is hidden; you won't see anything as you paste)"
read -rsp " DEEPSEEK_API_KEY: " API_KEY
echo
API_KEY="$(echo "$API_KEY" | tr -d '[:space:]')"
if [ -z "$API_KEY" ]; then
  echo " no api key entered — aborting"
  exit 1
fi

# Write env file with restricted perms
umask 077
{
  echo "# DeepSeek API credentials — stored only."
  echo "# Generated by scripts/qsb_set_deepseek_keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# DO NOT commit. The execution gates (direct_provider_access, model_inference_enabled)"
  echo "# remain FALSE in CLAUDE.md V1.5 — storage only."
  echo "DEEPSEEK_API_KEY=$API_KEY"
  echo "DEEPSEEK_BASE_URL=$DEEPSEEK_BASE"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo " wrote $ENV_FILE  (mode 600, owner-only)"

# Make sure .gitignore covers it
if [ -f "$GITIGNORE" ] && ! grep -qE '^\.env(\.|$|\*)' "$GITIGNORE"; then
  {
    echo ""
    echo "# QSB Tower — env files with credentials. Never commit."
    echo ".env"
    echo ".env.*"
    echo "floors/floor_28_security_department/vault/"
  } >> "$GITIGNORE"
  echo " added .env coverage to .gitignore"
fi

# Smoke test — read-only call (GET /models)
echo
echo " Testing key against $DEEPSEEK_BASE/models ..."
set +e
CODE=$(curl -s -o /tmp/qsb_deepseek_test.json -w "%{http_code}" \
  -H "Authorization: Bearer $API_KEY" \
  "$DEEPSEEK_BASE/models" 2>/dev/null)
set -e

if [ "$CODE" = "200" ]; then
  echo " ✓ key verified against DeepSeek (HTTP 200)"
  if command -v python3 >/dev/null 2>&1; then
    python3 -c "
import json
try:
    d = json.load(open('/tmp/qsb_deepseek_test.json'))
    models = [m.get('id','') for m in d.get('data', [])]
    print(f'   models the key can list: {len(models)}')
    print(f'   sample: {models[:6]}')
except Exception as e:
    print(f'   parse error: {e}')
"
  fi
else
  echo " ✗ key test failed (HTTP $CODE)"
  echo "   response: $(head -c 240 /tmp/qsb_deepseek_test.json)"
  echo
  echo "   common causes:"
  echo "    · expired or revoked key"
  echo "    · billing not active on the account"
  exit 2
fi
rm -f /tmp/qsb_deepseek_test.json

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Key stored and verified — but DORMANT."
echo
echo " To make any code actually call DeepSeek with this key, you must:"
echo "   1. Edit CLAUDE.md V1.5 forbidden-actions list"
echo "   2. Flip direct_provider_access / model_inference_enabled gates"
echo "   3. Write code that reads os.environ['DEEPSEEK_API_KEY']"
echo " Until then the key sits in the vault, gitignored, owner-only."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
