#!/usr/bin/env bash
# qsb_set_binance_testnet_keys.sh
#
# Interactive helper to install Binance TESTNET API credentials
# for Floor 42's testnet placement engine.
#
#   * Reads keys from your terminal — silent input, never echoed.
#   * Writes /vaults/nvme0/qsb_tower_v1/.env.binance_testnet
#   * chmod 600 on the env file (owner-read/write only).
#   * Ensures .gitignore excludes .env*.
#   * Smoke-tests the keys via a read-only signed call to testnet.
#
# This script is for the TESTNET only (testnet.binance.vision).
# Get testnet keys from https://testnet.binance.vision — these are
# NOT your real Binance.com keys, and they trade fake money only.
#
# Re-run any time to overwrite. Existing values are not displayed.

set -euo pipefail

ROOT="/vaults/nvme0/qsb_tower_v1"
VAULT_DIR="$ROOT/floors/floor_28_security_department/vault"
ENV_FILE="$VAULT_DIR/.env.binance_testnet"
GITIGNORE="$ROOT/.gitignore"
TESTNET_URL="https://testnet.binance.vision"

mkdir -p "$VAULT_DIR" && chmod 700 "$VAULT_DIR"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Binance TESTNET key installer · QSB Tower Floor 42"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
echo " You are about to install TESTNET keys (fake money)."
echo " Get them from: https://testnet.binance.vision"
echo " DO NOT paste keys from binance.com here — those control real money"
echo " and this script does not gate real-money execution."
echo
read -rp " Continue? [y/N] " confirm
case "$confirm" in
  y|Y|yes|YES) ;;
  *) echo " aborted."; exit 1 ;;
esac

# Read the API key — visible, since it isn't sensitive on its own
echo
echo " Paste your TESTNET API KEY then press Enter."
echo " (this is the 'API Key' string from testnet.binance.vision)"
read -rp " API KEY: " API_KEY
API_KEY="$(echo "$API_KEY" | tr -d '[:space:]')"
if [ -z "$API_KEY" ]; then
  echo " no api key entered — aborting"
  exit 1
fi

# Read the secret — silent, never echoed, never in history
echo
echo " Paste your TESTNET API SECRET then press Enter."
echo " (input is hidden; you won't see anything as you paste)"
read -rsp " API SECRET: " API_SECRET
echo
API_SECRET="$(echo "$API_SECRET" | tr -d '[:space:]')"
if [ -z "$API_SECRET" ]; then
  echo " no api secret entered — aborting"
  exit 1
fi

# Write the env file with restricted perms
umask 077
cat > "$ENV_FILE" <<EOF
# Binance TESTNET credentials — fake money only.
# Generated by scripts/qsb_set_binance_testnet_keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# DO NOT commit. DO NOT share. DO NOT put real-money keys here.
QSB_BINANCE_TESTNET_API_KEY=$API_KEY
QSB_BINANCE_TESTNET_API_SECRET=$API_SECRET
QSB_BINANCE_TESTNET_URL=$TESTNET_URL
EOF
chmod 600 "$ENV_FILE"
echo " wrote $ENV_FILE  (mode 600, owner-only)"

# Make sure .gitignore covers it
if [ -f "$GITIGNORE" ]; then
  if ! grep -qE '^\.env(\.|$|\*)' "$GITIGNORE"; then
    {
      echo ""
      echo "# QSB Tower — env files with credentials. Never commit."
      echo ".env"
      echo ".env.*"
    } >> "$GITIGNORE"
    echo " added .env / .env.* to .gitignore"
  else
    echo " .gitignore already covers .env files"
  fi
else
  cat > "$GITIGNORE" <<'EOF'
# QSB Tower — env files with credentials. Never commit.
.env
.env.*
EOF
  echo " created .gitignore with .env coverage"
fi

# Smoke test — read-only signed call (GET /api/v3/account)
echo
echo " Testing keys against $TESTNET_URL/api/v3/account ..."
set +e
TS=$(($(date +%s%N) / 1000000))
SIG=$(echo -n "timestamp=$TS" | openssl dgst -sha256 -hmac "$API_SECRET" | sed 's/^.* //')
CODE=$(curl -s -o /tmp/qsb_binance_test.json -w "%{http_code}" \
  -H "X-MBX-APIKEY: $API_KEY" \
  "$TESTNET_URL/api/v3/account?timestamp=$TS&signature=$SIG" 2>/dev/null)
set -e

if [ "$CODE" = "200" ]; then
  echo " ✓ keys verified against testnet (HTTP 200)"
  # Show a tiny non-sensitive proof: account type + permissions
  if command -v python3 >/dev/null 2>&1; then
    python3 -c "
import json
try:
    d = json.load(open('/tmp/qsb_binance_test.json'))
    print(f'   account type: {d.get(\"accountType\",\"—\")}')
    print(f'   permissions: {d.get(\"permissions\",[])}')
    print(f'   balances tracked: {len(d.get(\"balances\",[]))}')
except Exception as e:
    print(f'   (parse error: {e})')
"
  fi
else
  echo " ✗ key test failed (HTTP $CODE)"
  echo "   response: $(head -c 240 /tmp/qsb_binance_test.json)"
  echo
  echo "   common causes:"
  echo "    · keys from binance.com (real) used against testnet → wrong"
  echo "    · keys expired or revoked"
  echo "    · system clock drift"
  exit 2
fi
rm -f /tmp/qsb_binance_test.json

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Keys installed and verified."
echo
echo " The dashboard launcher (scripts/qsb_dashboard_start.sh) auto-sources"
echo " this file via:   set -a; . ./.env.binance_testnet; set +a"
echo
echo " If your launcher does not already do this, add this near the top:"
echo "   if [ -f .env.binance_testnet ]; then set -a; . ./.env.binance_testnet; set +a; fi"
echo
echo " To use now in your current shell:"
echo "   set -a; source .env.binance_testnet; set +a"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
