#!/usr/bin/env bash
# qsb_set_openai_keys.sh
#
# Interactive helper to install OpenAI API credentials into the Floor 28 vault.
#
# IMPORTANT:
#   Storing the key DOES NOT enable provider execution. CLAUDE.md V1.5 keeps
#   these gates locked false:
#     · direct_provider_access
#     · external_provider_execution_enabled
#     · model_inference_enabled
#   The key sits in the vault. Nothing in the codebase calls OpenAI today.
#   To USE the key, those gates need to be flipped via a CLAUDE.md edit
#   (not a verbal directive).
#
# What this script does:
#   1. Confirms storage intent
#   2. Reads OPENAI_API_KEY (hidden) and optional OPENAI_ORG_ID (visible)
#   3. Writes floors/floor_28_security_department/vault/.env.openai (chmod 600)
#   4. Tests via GET /v1/models (read-only; lists which models the key can use)
#   5. Reports back with no key material in stdout/logs

set -euo pipefail

ROOT="/vaults/nvme0/qsb_tower_v1"
VAULT_DIR="$ROOT/floors/floor_28_security_department/vault"
ENV_FILE="$VAULT_DIR/.env.openai"
GITIGNORE="$ROOT/.gitignore"
OPENAI_BASE="https://api.openai.com"

mkdir -p "$VAULT_DIR" && chmod 700 "$VAULT_DIR"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " OpenAI key installer · QSB Tower Floor 28 vault"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
echo " This stores the key. It does NOT enable provider access."
echo " direct_provider_access stays FALSE — no code calls OpenAI today."
echo
read -rp " Continue? [y/N] " confirm
case "$confirm" in
  y|Y|yes|YES) ;;
  *) echo " aborted."; exit 1 ;;
esac

# Optional org/project id (visible)
echo
echo " Optional: paste your OPENAI_ORG_ID (org-...) or just press Enter to skip."
read -rp " OPENAI_ORG_ID: " ORG_ID
ORG_ID="$(echo "$ORG_ID" | tr -d '[:space:]')"

# Hidden API key
echo
echo " Paste your OPENAI_API_KEY (sk-... or sk-proj-...) then press Enter."
echo " (input is hidden; you won't see anything as you paste)"
read -rsp " OPENAI_API_KEY: " API_KEY
echo
API_KEY="$(echo "$API_KEY" | tr -d '[:space:]')"
if [ -z "$API_KEY" ]; then
  echo " no api key entered — aborting"
  exit 1
fi

# Write env file with restricted perms
umask 077
{
  echo "# OpenAI API credentials — stored only."
  echo "# Generated by scripts/qsb_set_openai_keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# DO NOT commit. The execution gates (direct_provider_access, model_inference_enabled)"
  echo "# remain FALSE in CLAUDE.md V1.5 — storage only."
  echo "OPENAI_API_KEY=$API_KEY"
  if [ -n "$ORG_ID" ]; then
    echo "OPENAI_ORG_ID=$ORG_ID"
  fi
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo " wrote $ENV_FILE  (mode 600, owner-only)"

# Make sure .gitignore covers it
if [ -f "$GITIGNORE" ] && ! grep -qE '^\.env(\.|$|\*)' "$GITIGNORE"; then
  {
    echo ""
    echo "# QSB Tower — env files with credentials. Never commit."
    echo ".env"
    echo ".env.*"
    echo "floors/floor_28_security_department/vault/"
  } >> "$GITIGNORE"
  echo " added .env coverage to .gitignore"
fi

# Smoke test — read-only call (GET /v1/models)
echo
echo " Testing key against $OPENAI_BASE/v1/models ..."
set +e
ORG_HEADER=""
if [ -n "$ORG_ID" ]; then
  ORG_HEADER="-H OpenAI-Organization: $ORG_ID"
fi
# shellcheck disable=SC2086
CODE=$(curl -s -o /tmp/qsb_openai_test.json -w "%{http_code}" \
  -H "Authorization: Bearer $API_KEY" \
  $ORG_HEADER \
  "$OPENAI_BASE/v1/models" 2>/dev/null)
set -e

if [ "$CODE" = "200" ]; then
  echo " ✓ key verified against OpenAI (HTTP 200)"
  if command -v python3 >/dev/null 2>&1; then
    python3 -c "
import json
try:
    d = json.load(open('/tmp/qsb_openai_test.json'))
    models = [m.get('id','') for m in d.get('data', [])]
    chat_capable = [m for m in models if any(x in m for x in ['gpt-','o1-','o3','o4'])]
    print(f'   total models the key can list: {len(models)}')
    print(f'   chat-capable models: {len(chat_capable)}  (sample: {chat_capable[:4]})')
except Exception as e:
    print(f'   parse error: {e}')
"
  fi
else
  echo " ✗ key test failed (HTTP $CODE)"
  echo "   response: $(head -c 240 /tmp/qsb_openai_test.json)"
  echo
  echo "   common causes:"
  echo "    · expired or revoked key"
  echo "    · org ID mismatch"
  echo "    · billing not active on the account"
  exit 2
fi
rm -f /tmp/qsb_openai_test.json

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Key stored and verified — but DORMANT."
echo
echo " To make any code actually call OpenAI with this key, you must:"
echo "   1. Edit CLAUDE.md V1.5 forbidden-actions list"
echo "   2. Flip direct_provider_access / model_inference_enabled gates"
echo "   3. Write code that reads os.environ['OPENAI_API_KEY']"
echo " Until then the key sits in the vault, gitignored, owner-only."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
