#!/usr/bin/env bash
#
# QSB Tower V1.3 — Floor 43 Alpaca credential helper
#
# Writes /vaults/nvme0/qsb_tower_v1/.env.alpaca with chmod 600.
# Secret is read via hidden input.
# Secret is never echoed.
# Secret is never printed in confirmation output.
# Secret is never written to any file other than .env.alpaca.

set -eu

ROOT="${QSB_TOWER_ROOT:-/vaults/nvme0/qsb_tower_v1}"
ENV_FILE="$ROOT/.env.alpaca"

echo "======================================================"
echo "  QSB Tower V1.3 — Floor 43 Alpaca Credential Setup"
echo "======================================================"
echo "Writes .env.alpaca with chmod 600. Secret is hidden input only."
echo "No secret is ever echoed or logged."
echo

# --- ALPACA_API_KEY (visible — it is the public-facing identifier)
printf "ALPACA_API_KEY (visible) [leave blank to keep current]: "
IFS= read -r ALPACA_API_KEY_INPUT || true

# --- ALPACA_API_SECRET (hidden)
printf "ALPACA_API_SECRET (hidden input, leave blank to keep current): "
IFS= read -rs ALPACA_API_SECRET_INPUT || true
echo
printf "Confirm ALPACA_API_SECRET (hidden, leave blank to keep current): "
IFS= read -rs ALPACA_API_SECRET_CONFIRM || true
echo

if [ -n "$ALPACA_API_SECRET_INPUT" ] || [ -n "$ALPACA_API_SECRET_CONFIRM" ]; then
  if [ "$ALPACA_API_SECRET_INPUT" != "$ALPACA_API_SECRET_CONFIRM" ]; then
    echo "ERROR: secret confirmation did not match. Aborting. Nothing was written." >&2
    unset ALPACA_API_SECRET_INPUT ALPACA_API_SECRET_CONFIRM
    exit 1
  fi
fi

# --- ALPACA_ENV (paper / live_data_readonly)
printf "ALPACA_ENV [paper/live_data_readonly, default=paper]: "
IFS= read -r ALPACA_ENV_INPUT || true
case "${ALPACA_ENV_INPUT:-}" in
  ""|paper|PAPER)                       ALPACA_ENV_VALUE="paper" ;;
  live_data_readonly|LIVE_DATA_READONLY)ALPACA_ENV_VALUE="live_data_readonly" ;;
  *)
    echo "ERROR: ALPACA_ENV must be 'paper' or 'live_data_readonly'. Got: $ALPACA_ENV_INPUT" >&2
    unset ALPACA_API_SECRET_INPUT ALPACA_API_SECRET_CONFIRM
    exit 1
    ;;
esac

# --- ALPACA_READ_ONLY (true/false; we strongly default to true)
printf "ALPACA_READ_ONLY [true/false, default=true]: "
IFS= read -r ALPACA_READ_ONLY_INPUT || true
case "${ALPACA_READ_ONLY_INPUT:-}" in
  ""|true|TRUE)  ALPACA_READ_ONLY_VALUE="true" ;;
  false|FALSE)   ALPACA_READ_ONLY_VALUE="false" ;;
  *)
    echo "ERROR: ALPACA_READ_ONLY must be 'true' or 'false'." >&2
    unset ALPACA_API_SECRET_INPUT ALPACA_API_SECRET_CONFIRM
    exit 1
    ;;
esac

# --- preserve existing values if user left fields blank
existing_key=""
existing_secret=""
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  existing_key="$(grep -E '^(export +)?ALPACA_API_KEY=' "$ENV_FILE" | tail -n1 | sed -E 's/^(export +)?ALPACA_API_KEY=//; s/^"//; s/"$//; s/^'\''//; s/'\''$//' || true)"
  existing_secret="$(grep -E '^(export +)?ALPACA_API_SECRET=' "$ENV_FILE" | tail -n1 | sed -E 's/^(export +)?ALPACA_API_SECRET=//; s/^"//; s/"$//; s/^'\''//; s/'\''$//' || true)"
fi

FINAL_KEY="${ALPACA_API_KEY_INPUT:-$existing_key}"
FINAL_SECRET="${ALPACA_API_SECRET_INPUT:-$existing_secret}"

umask 077
tmpfile="$(mktemp "${ENV_FILE}.XXXXXX")"
trap 'rm -f "$tmpfile"' EXIT
{
  echo "# QSB Tower V1.3 — Floor 43 Alpaca credentials"
  echo "# Generated by scripts/setup_alpaca_env.sh"
  echo "# chmod 600 enforced. Do not commit this file."
  echo "export ALPACA_ENV='${ALPACA_ENV_VALUE}'"
  echo "export ALPACA_READ_ONLY='${ALPACA_READ_ONLY_VALUE}'"
  echo "export ALPACA_ORDER_EXECUTION_ENABLED='false'"
  echo "export ALPACA_API_KEY='${FINAL_KEY}'"
  echo "export ALPACA_API_SECRET='${FINAL_SECRET}'"
} > "$tmpfile"
chmod 600 "$tmpfile"
mv "$tmpfile" "$ENV_FILE"
trap - EXIT

unset ALPACA_API_SECRET_INPUT ALPACA_API_SECRET_CONFIRM FINAL_SECRET existing_secret

echo
echo "Wrote: $ENV_FILE (chmod 600)"
echo "  ALPACA_ENV                       = ${ALPACA_ENV_VALUE}"
echo "  ALPACA_READ_ONLY                 = ${ALPACA_READ_ONLY_VALUE}"
echo "  ALPACA_ORDER_EXECUTION_ENABLED   = false"
echo "  ALPACA_API_KEY                   = $([ -n "$FINAL_KEY" ] && echo present || echo MISSING)"
echo "  ALPACA_API_SECRET                = $(grep -E '^(export +)?ALPACA_API_SECRET=' "$ENV_FILE" >/dev/null && echo present || echo MISSING)"
echo
echo "Permissions:"
stat -c '  %A  %U  %n' "$ENV_FILE"
echo
echo "Note: Stock order endpoints remain blocked at the gateway layer"
echo "      regardless of ALPACA_ORDER_EXECUTION_ENABLED in V1."
