#!/usr/bin/env bash
#
# QSB Tower V1.3 — Floor 42 Binance credential helper
#
# Writes /vaults/nvme0/qsb_tower_v1/.env.binance with chmod 600.
# Secret is read via hidden input.
# Secret is never echoed.
# Secret is never printed in confirmation output.
# Secret is never written to any file other than .env.binance.

set -eu

ROOT="${QSB_TOWER_ROOT:-/vaults/nvme0/qsb_tower_v1}"
ENV_FILE="$ROOT/.env.binance"

echo "======================================================"
echo "  QSB Tower V1.3 — Floor 42 Binance Credential Setup"
echo "======================================================"
echo "Writes .env.binance with chmod 600. Secret is hidden input only."
echo "No secret is ever echoed or logged."
echo

# --- BINANCE_API_KEY (visible — it is the public-facing identifier)
printf "BINANCE_API_KEY (visible) [leave blank to keep current]: "
IFS= read -r BINANCE_API_KEY_INPUT || true

# --- BINANCE_API_SECRET (hidden)
printf "BINANCE_API_SECRET (hidden input, leave blank to keep current): "
# -s: silent, -r: raw
IFS= read -rs BINANCE_API_SECRET_INPUT || true
echo
printf "Confirm BINANCE_API_SECRET (hidden, leave blank to keep current): "
IFS= read -rs BINANCE_API_SECRET_CONFIRM || true
echo

if [ -n "$BINANCE_API_SECRET_INPUT" ] || [ -n "$BINANCE_API_SECRET_CONFIRM" ]; then
  if [ "$BINANCE_API_SECRET_INPUT" != "$BINANCE_API_SECRET_CONFIRM" ]; then
    echo "ERROR: secret confirmation did not match. Aborting. Nothing was written." >&2
    unset BINANCE_API_SECRET_INPUT BINANCE_API_SECRET_CONFIRM
    exit 1
  fi
fi

# --- BINANCE_ENV (testnet/live)
printf "BINANCE_ENV [testnet/live, default=testnet]: "
IFS= read -r BINANCE_ENV_INPUT || true
case "${BINANCE_ENV_INPUT:-}" in
  ""|testnet|TESTNET) BINANCE_ENV_VALUE="testnet" ;;
  live|LIVE)          BINANCE_ENV_VALUE="live" ;;
  *)
    echo "ERROR: BINANCE_ENV must be 'testnet' or 'live'. Got: $BINANCE_ENV_INPUT" >&2
    unset BINANCE_API_SECRET_INPUT BINANCE_API_SECRET_CONFIRM
    exit 1
    ;;
esac

# --- BINANCE_READ_ONLY
printf "BINANCE_READ_ONLY [true/false, default=true]: "
IFS= read -r BINANCE_READ_ONLY_INPUT || true
case "${BINANCE_READ_ONLY_INPUT:-}" in
  ""|true|TRUE)  BINANCE_READ_ONLY_VALUE="true" ;;
  false|FALSE)   BINANCE_READ_ONLY_VALUE="false" ;;
  *)
    echo "ERROR: BINANCE_READ_ONLY must be 'true' or 'false'." >&2
    unset BINANCE_API_SECRET_INPUT BINANCE_API_SECRET_CONFIRM
    exit 1
    ;;
esac

# --- preserve existing values if user left fields blank
existing_key=""
existing_secret=""
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  existing_key="$(grep -E '^(export +)?BINANCE_API_KEY=' "$ENV_FILE" | tail -n1 | sed -E 's/^(export +)?BINANCE_API_KEY=//; s/^"//; s/"$//; s/^'\''//; s/'\''$//' || true)"
  existing_secret="$(grep -E '^(export +)?BINANCE_API_SECRET=' "$ENV_FILE" | tail -n1 | sed -E 's/^(export +)?BINANCE_API_SECRET=//; s/^"//; s/"$//; s/^'\''//; s/'\''$//' || true)"
fi

FINAL_KEY="${BINANCE_API_KEY_INPUT:-$existing_key}"
FINAL_SECRET="${BINANCE_API_SECRET_INPUT:-$existing_secret}"

umask 077
tmpfile="$(mktemp "${ENV_FILE}.XXXXXX")"
trap 'rm -f "$tmpfile"' EXIT
{
  echo "# QSB Tower V1.3 — Floor 42 Binance credentials"
  echo "# Generated by scripts/setup_binance_env.sh"
  echo "# chmod 600 enforced. Do not commit this file."
  echo "export BINANCE_ENV='${BINANCE_ENV_VALUE}'"
  echo "export BINANCE_READ_ONLY='${BINANCE_READ_ONLY_VALUE}'"
  echo "export BINANCE_ORDER_EXECUTION_ENABLED='false'"
  echo "export BINANCE_API_KEY='${FINAL_KEY}'"
  echo "export BINANCE_API_SECRET='${FINAL_SECRET}'"
} > "$tmpfile"
chmod 600 "$tmpfile"
mv "$tmpfile" "$ENV_FILE"
trap - EXIT

unset BINANCE_API_SECRET_INPUT BINANCE_API_SECRET_CONFIRM FINAL_SECRET existing_secret

echo
echo "Wrote: $ENV_FILE (chmod 600)"
echo "  BINANCE_ENV                      = ${BINANCE_ENV_VALUE}"
echo "  BINANCE_READ_ONLY                = ${BINANCE_READ_ONLY_VALUE}"
echo "  BINANCE_ORDER_EXECUTION_ENABLED  = false"
echo "  BINANCE_API_KEY                  = $([ -n "$FINAL_KEY" ] && echo present || echo MISSING)"
echo "  BINANCE_API_SECRET               = $(grep -E '^(export +)?BINANCE_API_SECRET=' "$ENV_FILE" >/dev/null && echo present || echo MISSING)"
echo
echo "Permissions:"
stat -c '  %A  %U  %n' "$ENV_FILE"
echo
echo "Note: Binance order endpoints remain blocked at the gateway layer"
echo "      regardless of BINANCE_ORDER_EXECUTION_ENABLED in V1."
