#!/usr/bin/env python3
"""qsb_github_daily_push.py — daily push of web/shops/ to
github.com/devon3dp/skyscraperhq, with hardcoded safety gating.

Ross 2026-06-20: "we need a daily push to github". Memory at
reference_github_skyscraperhq.md spells out scope + safety rules.

Run modes:
  python3 tools/qsb_github_daily_push.py            # honors 23h cooldown
  python3 tools/qsb_github_daily_push.py --force    # push regardless
  python3 tools/qsb_github_daily_push.py --dry-run  # report what would push, no commit

Safety (HARD, refuses to proceed otherwise):
  - SCOPE: only web/shops/ is in scope. Tool refuses if cwd or shops dir
    looks wrong, or if it sees any .env / vault / token / secret / pem / key
    in the staged set.
  - .gitignore is overwritten each run with the pinned safety block so a
    drifted .gitignore can never re-include a denied path.
  - Refuses if repo URL is not github.com/devon3dp/skyscraperhq.

Cooldown:
  - Reads data/registries/qsb_github_last_push.json. If last_run < 23h,
    exits without push unless --force. This lets the systemd timer fire
    every hour and still only push at most once per day.

Logs:
  - F47 row + diary line per push.
  - Updates qsb_github_last_push.json with commit + ts on success.
"""
from __future__ import annotations
import argparse, datetime, json, os, re, subprocess, sys
from pathlib import Path

ROOT = Path("/vaults/nvme0/qsb_tower_v1")
SHOPS = ROOT / "web" / "shops"
REG = ROOT / "data" / "registries"
LAST_PUSH = REG / "qsb_github_last_push.json"
F47 = REG / "qsb_f47_team_records.jsonl"
DIARY = REG / "qsb_session_diary.md"
EXPECTED_REMOTE = "git@github.com:devon3dp/skyscraperhq.git"

SAFETY_GITIGNORE = """# SAFETY — hardcoded blocks. Never push these regardless of structure.
# Regenerated by tools/qsb_github_daily_push.py every run.
.env*
**/.env*
**/vault/
**/secret*
**/*token*
**/*credential*
**/*.pem
**/*.key
node_modules/
.DS_Store
__pycache__/
"""

DENY_PATTERNS = re.compile(
    r"(\.env(?:\.|$)|/vault/|secret|token|credential|\.pem$|\.key$)",
    re.IGNORECASE,
)


def utc_iso() -> str:
    return datetime.datetime.now(datetime.UTC).isoformat().replace("+00:00", "Z")


def run(cmd, cwd=None, timeout=120, check=False):
    r = subprocess.run(cmd, cwd=str(cwd) if cwd else None, capture_output=True,
                       text=True, timeout=timeout)
    if check and r.returncode != 0:
        raise SystemExit(f"command failed: {' '.join(cmd)}\n{r.stderr}")
    return r


def cooldown_ok(force: bool) -> tuple[bool, str]:
    if force:
        return True, "force"
    if not LAST_PUSH.exists():
        return True, "no prior run"
    try:
        d = json.loads(LAST_PUSH.read_text())
        last = datetime.datetime.fromisoformat(d["ts"].replace("Z", "+00:00"))
    except Exception:
        return True, "last_push file unreadable, allowing"
    age_h = (datetime.datetime.now(datetime.UTC) - last).total_seconds() / 3600.0
    if age_h < 23:
        return False, f"last push {age_h:.1f}h ago (< 23h cooldown)"
    return True, f"last push {age_h:.1f}h ago"


def safety_audit() -> list[str]:
    """Walk web/shops/ and refuse if any path matches a deny pattern."""
    hits = []
    for root, dirs, files in os.walk(SHOPS):
        # Skip .git/
        dirs[:] = [d for d in dirs if d != ".git"]
        for f in files:
            full = Path(root) / f
            rel = full.relative_to(SHOPS).as_posix()
            if DENY_PATTERNS.search(rel) or DENY_PATTERNS.search(f):
                hits.append(rel)
    return hits


def stamp_f47(commit: str, files_changed: int, ran_mode: str):
    row = {
        "ts": utc_iso(),
        "kind": "github_repo_pushed",
        "role": "claude",
        "summary": f"Daily push {commit[:7]} to github.com/devon3dp/skyscraperhq main. "
                   f"{files_changed} files changed. Mode: {ran_mode}.",
        "repo_url": "https://github.com/devon3dp/skyscraperhq",
        "commit": commit,
        "files_changed": files_changed,
        "mode": ran_mode,
        "advisory_only": False,
    }
    F47.parent.mkdir(parents=True, exist_ok=True)
    with F47.open("a") as f:
        f.write(json.dumps(row) + "\n")


def append_diary(commit: str, n: int):
    line = (f"- {datetime.datetime.now(datetime.UTC).strftime('%H:%M UTC (%Y-%m-%d)')} "
            f"— GitHub daily push: commit {commit[:7]} to devon3dp/skyscraperhq, "
            f"{n} files. Auto via tools/qsb_github_daily_push.py.\n")
    DIARY.parent.mkdir(parents=True, exist_ok=True)
    with DIARY.open("a") as f:
        f.write(line)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="bypass 23h cooldown")
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would push, no commit")
    args = ap.parse_args()

    # ── COOLDOWN ───────────────────────────────────────────────
    ok, why = cooldown_ok(args.force)
    if not ok:
        print(f"cooldown: skipping ({why})")
        return 0
    print(f"cooldown: {why} → proceeding")

    # ── PREREQUISITES ──────────────────────────────────────────
    if not SHOPS.exists():
        print(f"ERROR: shops dir missing at {SHOPS}", file=sys.stderr)
        return 2
    git_dir = SHOPS / ".git"
    if not git_dir.exists():
        print(f"git init {SHOPS}")
        run(["git", "init", "-q"], cwd=SHOPS, check=True)
        run(["git", "remote", "add", "origin", EXPECTED_REMOTE],
            cwd=SHOPS, check=True)

    # ── VERIFY REMOTE ──────────────────────────────────────────
    r = run(["git", "remote", "get-url", "origin"], cwd=SHOPS)
    remote = r.stdout.strip()
    if remote != EXPECTED_REMOTE:
        print(f"ERROR: remote is {remote!r}, expected {EXPECTED_REMOTE!r}",
              file=sys.stderr)
        return 3

    # ── PIN SAFETY .gitignore ──────────────────────────────────
    (SHOPS / ".gitignore").write_text(SAFETY_GITIGNORE)

    # ── SAFETY AUDIT ───────────────────────────────────────────
    hits = safety_audit()
    if hits:
        print(f"ABORT: safety audit found {len(hits)} disallowed path(s):",
              file=sys.stderr)
        for h in hits[:10]:
            print(f"  • {h}", file=sys.stderr)
        return 4

    # ── FETCH + STAGE ──────────────────────────────────────────
    run(["git", "fetch", "origin"], cwd=SHOPS, check=True)
    run(["git", "add", "-A"], cwd=SHOPS, check=True)
    diff = run(["git", "status", "--short"], cwd=SHOPS).stdout.splitlines()
    n_changed = len(diff)
    if n_changed == 0:
        print("nothing changed — skipping commit/push")
        # Still update last_push so we don't re-try immediately
        LAST_PUSH.write_text(json.dumps({
            "ts": utc_iso(), "commit": None,
            "files_changed": 0, "result": "nothing_to_push",
        }, indent=2))
        return 0

    print(f"{n_changed} files changed; about to commit")
    if args.dry_run:
        print("DRY RUN — would commit + push the above")
        return 0

    # ── COMMIT + PUSH ──────────────────────────────────────────
    date_str = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d")
    msg = (f"Daily push {date_str} — {n_changed} files updated\n\n"
           f"Auto via tools/qsb_github_daily_push.py\n\n"
           f"Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>")
    r = run(["git", "commit", "-m", msg], cwd=SHOPS)
    if r.returncode != 0:
        # Could be "nothing to commit" race
        print(f"commit step: rc={r.returncode}\n{r.stderr}")
        if "nothing to commit" in (r.stderr + r.stdout):
            return 0
        return 5
    commit = run(["git", "rev-parse", "HEAD"], cwd=SHOPS).stdout.strip()

    # Determine branch (default main; init may have left HEAD off-branch)
    r = run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=SHOPS)
    branch = r.stdout.strip()
    if branch == "HEAD":
        run(["git", "branch", "-M", "main"], cwd=SHOPS, check=True)
        branch = "main"
    push = run(["git", "push", "origin", branch], cwd=SHOPS)
    if push.returncode != 0:
        print(f"push FAILED rc={push.returncode}\n{push.stderr}", file=sys.stderr)
        return 6
    print(f"pushed {commit[:7]} to origin/{branch} ({n_changed} files)")

    # ── RECORDS ────────────────────────────────────────────────
    LAST_PUSH.write_text(json.dumps({
        "ts": utc_iso(), "commit": commit, "branch": branch,
        "files_changed": n_changed, "result": "pushed",
    }, indent=2))
    mode = "force" if args.force else "cooldown_ok"
    stamp_f47(commit, n_changed, mode)
    append_diary(commit, n_changed)
    return 0


if __name__ == "__main__":
    sys.exit(main())
